version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - /var/mysql:/var/lib/mysql
    networks:
      - app_network

  rust_app:
    image: rust-sea-orm
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "mysql://root:123456@mysql/test"
    volumes:
      - ./target:/app
    networks:
      - app_network
    command: "tail -f /dev/null"
    depends_on:
      - mysql

  adminer:
    image: adminer:latest
    ports:
      - "8079:8080"
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
