//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::bakery::Entity as Bakery;
pub use super::cake::Entity as Cake;
pub use super::cake_filling::Entity as CakeFilling;
pub use super::chef::Entity as Chef;
pub use super::filling::Entity as Filling;
pub use super::fruit::Entity as Fruit;
